### ISSUE TITLE
NP Demo TODO list

### ISSUE THREAD

**Issue by afq984** [zlsh80826/Shape-War#34]
- [x] Experience bar bug #32 
- [ ] Network latency problems,  don't send dead
- [x] Allow user to specify name & rework login #33
- [ ] Implement chat, unclickable
- [x] Do not bound bullet #37 
- [x] Respawn bug #38
- [x] Object vibration bug
- [x] After death?

**Comment by Nash2325138** [comment]
"Allow user to specify name & rework login"
I don't quite understand the meaning of this requirement

**Comment by afq984** [comment]
Something like this

Login Dialog

```
address:  [            ]
port:     [            ]
nickname: [            ]

           [ Join Game ]
```

Process:
- client sends a HTTP POST to server
- server sends the token back to client
- client joins game with corresponding nickname
- client joins chat room with corresponding nickname
